require("core.opts")
require("core.keymaps")

require("plugins.treesitter")
require("plugins.lsp")
require("plugins.completion")
require("plugins.formatting")
require("plugins.theme")
require("plugins.snacks")
require("plugins.tmux-navigation")
require("plugins.git")
require("plugins.statusline")
require("plugins.noice")

vim.cmd("colorscheme rose-pine")
