-- Add autocmds here in this folder with `nvim_create_autocmd`
-- This init.lua file should be used to required all of the modules inside this
-- folder.
--
-- example
-- vim.api.nvim_create_autocmd("TextYankPost", {})
